version: '3'
services:
  app:
    image: #STACKNAME#:test
    container_name: #STACKNAME#
    restart: always
    extra_hosts:
      - "app-host:192.168.2.65"
      - "redis.syfintech.cn:172.21.21.68"
      - "rabbitmq.syfintech.cn:172.21.21.68"
      - "eureka.instance.cn:172.21.21.68"
      - "eureka.instance.cn2:172.21.21.68"
      - "eureka.instance.cn3:172.21.21.68"
      - "admin.url.syfintech.cn:172.21.21.68"
      - "jdbc.mysql.dcpms.cn:172.21.21.67"
      - "tracker-server:172.21.21.12"
    volumes:
      - ./logs:/root/dcpms/logs/#STACKNAME#
    environment:
      - JAVA_OPTS=-Xmx256m -Xms256m -Dfile.encoding=UTF-8
      - SPRING_PROFILE=test
    network_mode: host

